--UNABLE TO WRITE THE QUERY FOR STORED PROCEDURE--


create table tableOFC100(
	ID_Num int,
	name varchar(500),
	location varchar(500)
);

insert into tableOFC100 (ID_NUM , NAME, LOCATION) values
 (101, 'KUMAR', 'BTM1'),
 (102, 'PRASANNA', 'BTM2'),
 (103, 'KUMAR PRASANNA', 'BTM1'),
 (104, 'PK', 'BTM2');

SELECT *
FROM TABLEOFC100

create table tableOFC101(
	ID_Num int,
	DEPT varchar(500),
	MGR varchar(500)
);

insert into tableOFC101 (ID_NUM , DEPT, MGR) values
 (101, 'ECE', 'M1'),
 (102, 'CIVIL', 'M2'),
 (103, 'ECE', 'M3'),
 (104, 'CIVIL', 'M1');
 
 SELECT *
FROM TABLEOFC101

select *
FROM TABLEOFC100
WHERE ID_NUM IN(select ID_NUM FROM TABLEOFC101 WHERE MGR IN('M1','M2'))


select TABLEOFC100.NAME
FROM TABLEOFC100 INNER JOIN TABLEOFC101
ON TABLEOFC100.ID_NUM = TABLEOFC101.ID_NUM


select *
FROM TABLEOFC100 LEFT JOIN TABLEOFC101
ON TABLEOFC100.ID_NUM = TABLEOFC101.ID_NUM
ORDER BY TABLEOFC100.LOCATION

select DISTINCT *
FROM TABLEOFC100 AS T1, TABLEOFC100 AS T2
WHERE T1.ID_NUM<>T2.ID_NUM
ORDER BY T1.LOCATION

select ID_NUM
FROM TABLEOFC100 
WHERE LOCATION = 'BTM1'
GROUP BY ID_NUM;

SELECT LOCATION
CASE
WHERE LOCATION = 'BTM1' THEN LOCATION
ELSE NULL
END 
FROM TABLEOFC100

CREATE PROCEDURE SelectAllCustomers 
AS
BEGIN
	SELECT * 
	FROM TABLEOFC100
END

-------------------------------------------------------------------------------------

CREATE DATABASE databasename;